import sanitizeHtml from 'sanitize-html';
import {ARCHIVE_SCHEMAS} from './archive-schemas.mjs';
export function previewURL(value,role){if(!value||value.startsWith('data:')||value==='about:blank')return value;const url=new URL(value,'https://local.test');if(url.origin!=='https://local.test')return '';const query=new URLSearchParams(url.search);query.set('role',role);if(url.pathname.startsWith('/api/')){if(url.pathname==='/api/evidence')query.set('type','evidence');}else query.set('path',url.pathname);return '/api/preview-files?'+query;}
export function previewState(state,role){const result=structuredClone(state);for(const d of result.documents)d.url=previewURL(d.url,role);for(const p of result.personnel){p.image=previewURL(p.image,role);if(p.attachment)p.attachment.url=previewURL(p.attachment.url,role);}for(const e of result.evidence)e.src=previewURL(e.src||'/api/evidence?id='+encodeURIComponent(e.id),role);if(result.directorSignature)result.directorSignature.image=previewURL(result.directorSignature.image,role);result.cityHtml=result.cityHtml.replace(/src="([^"]+)"/g,(_,url)=>'src="'+previewURL(url,role).replaceAll('&','&amp;')+'"');return result;}
const escape=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function previewHTML(html,state,id,role){
 const cleaned=sanitizeHtml(html,{allowedTags:[...sanitizeHtml.defaults.allowedTags,'html','head','body','title','style','img'],allowedAttributes:{'*':['class','id','style','title','lang'],img:['src','alt','width','height'],td:['colspan','rowspan'],th:['colspan','rowspan']},allowVulnerableTags:true,allowedSchemes:['https','data'],transformTags:{img:(tag,attrs)=>({tagName:tag,attribs:{...attrs,src:previewURL(attrs.src,role)}})}});
 const schema=ARCHIVE_SCHEMAS[id],entry=state.archiveEntries?.[id];if(!schema)return cleaned;
 const fields=schema.fields.map(f=>[f.label,entry?.content?.[f.id]??'미기록']);for(const [key,value]of Object.entries(entry?.content||{}))if(!schema.fields.some(f=>f.id===key))fields.push([key,value]);for(const [key,value]of Object.entries(entry?.signatures||{}))fields.push(['서명 · '+key,value]);
 return cleaned+'<section style="margin:24px;padding:24px;background:#fff;color:#183543;border:1px solid #789"><h2>'+escape(schema.title)+' · 저장 기록</h2><p>읽기 전용</p>'+fields.map(([label,value])=>'<h3>'+escape(label)+'</h3><p style="white-space:pre-wrap;overflow-wrap:anywhere">'+escape(value)+'</p>').join('')+'</section>';
}
